### ISSUE TITLE
You are sending out the wrong buffer

### ISSUE THREAD

**Issue by swalde** [BizTalkCommunity/BizTalk-PipelineComponents-Extensions-UtilityPack#3]
https://www.linkedin.com/in/stenwalde/

                    MemoryStream tempMemStream = new MemoryStream(**compressedPartBuffer); //currentPartBuffer)**;
                    pInMsg.BodyPart.Data = tempMemStream;

                    string sourcePartName = fileName.Substring(0, fileName.LastIndexOf('.')) + this.FileExtension; // fil.xml -> fil.zip (including '.')

                    pInMsg.Context.Promote("ReceivedFileName", "http://schemas.microsoft.com/BizTalk/2003/file-properties", sourcePartName);
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            return pInMsg;

            #endregion
        }
    }
}

**Comment by sandroasp** [comment]
Fixed that, thanks!
